import AxeBuilder from '@axe-core/playwright'
import { test, expect } from './fixtures'
import type { Page } from '@playwright/test'

const portable = (content = '# Shared rules\nKeep project overrides visible.\n') => JSON.stringify({format:'agentforge-template',version:1,template:{name:'Imported rules',provider:'codex',kind:'instructions',sourcePath:'AGENTS.md',tags:['portable','team'],content}})
async function openProject(page: Page) {
 await page.goto('/')
 await page.getByLabel('Project directory', {exact:true}).fill('/projects/sample-project')
 await page.getByRole('button',{name:'Inspect project',exact:true}).click()
 await page.getByRole('button',{name:'AGENTS.md',exact:true}).click()
}
async function library(page: Page) { await page.getByRole('button',{name:'Template library',exact:true}).click() }

test('tagged templates are searchable and provider mismatches cannot be applied', async ({page}) => {
 await openProject(page)
 await page.getByText('Configuration templates', {exact:false}).filter({has:page.locator('.count')}).click()
 await page.getByLabel('New template name').fill('Go team rules')
 await page.getByLabel('Tags (optional, comma-separated)').fill('Golang, team')
 await page.getByRole('button',{name:'Save file as template'}).click()
 await library(page)
 await page.getByLabel('Search templates',{exact:true}).fill('golang')
 await expect(page.getByRole('heading',{name:'Go team rules',exact:true})).toBeVisible()
 await expect(page.getByRole('heading',{name:'Team defaults',exact:true})).toBeHidden()
 await page.getByLabel('Provider',{exact:true}).selectOption('claude')
 await expect(page.getByRole('heading',{name:'No matching templates'})).toBeVisible()
 await page.getByRole('button',{name:'Clear template filters'}).click()
 await page.getByRole('button',{name:/^Project configuration/}).click()
 await page.getByRole('button',{name:'.claude/agents/reviewer.md',exact:true}).click()
 await library(page)
 for(const button of await page.getByRole('button',{name:'Load into current file',exact:true}).all()) await expect(button).toBeDisabled()
 await page.getByRole('button',{name:'Export Go team rules',exact:true}).click()
 const output=page.getByLabel('Portable template JSON')
 await expect(output).toBeFocused()
 expect(JSON.parse(await output.inputValue()).template.tags).toEqual(['golang','team'])
 await expect(page.getByText('This export includes the complete native text.',{exact:false})).toBeVisible()
 expect(await page.evaluate(()=>(window as any).__calls)).toEqual(['save-template'])
})

test('import review is read-only, invalidated by edits, and survives navigation', async ({page}) => {
 await page.goto('/');await library(page)
 const input=page.getByLabel('Template JSON to review')
 await input.fill(portable())
 await page.getByRole('button',{name:'Review import',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Review: Imported rules'})).toBeFocused()
 expect(await page.evaluate(()=>(window as any).__calls)).toEqual([])
 await page.getByRole('button',{name:'Learning library',exact:true}).click()
 await library(page)
 await expect(input).toHaveValue(portable())
 await input.fill(portable('# Revised rules'))
 await expect(page.getByRole('button',{name:'Import reviewed template'})).toBeHidden()
 await page.getByRole('button',{name:'Review import',exact:true}).click()
 await page.getByRole('button',{name:'Import reviewed template'}).click()
 await expect(page.getByRole('status')).toContainText('No project files changed')
 await expect(input).toHaveValue('')
 await expect(page.getByRole('heading',{name:'Imported rules',exact:true})).toBeVisible()
 expect(await page.evaluate(()=>(window as any).__calls)).toEqual(['import-template'])
})

test('import errors preserve inputs and pending imports cannot be submitted twice', async ({page}) => {
 await page.goto('/');await library(page)
 await page.getByLabel('Template JSON to review').fill(portable())
 await page.getByRole('button',{name:'Review import',exact:true}).click()
 await page.evaluate(()=>{(window as any).__failImport=true;(window as any).__delayImport=300})
 const submit=page.getByRole('button',{name:'Import reviewed template'})
 await submit.click();await expect(submit).toBeDisabled()
 await expect(page.getByRole('alert')).toContainText('Library is not writable')
 await expect(page.getByLabel('Template JSON to review')).toHaveValue(portable())
 await expect(submit).toBeEnabled()
 await page.evaluate(()=>(window as any).__failImport=false)
 await submit.click()
 await expect(page.getByRole('status')).toContainText('Imported')
 expect(await page.evaluate(()=>(window as any).__calls)).toEqual(['import-template','import-template'])
})

test('unsupported envelopes and invalid native content cannot be imported', async ({page}) => {
 await page.goto('/');await library(page)
 const input=page.getByLabel('Template JSON to review')
 await input.fill('{"format":"other","version":9}')
 await page.getByRole('button',{name:'Review import',exact:true}).click()
 await expect(page.getByRole('alert')).toContainText('Unsupported template format')
 await input.fill(portable('INVALID'))
 await page.getByRole('button',{name:'Review import',exact:true}).click()
 await expect(page.getByText('Invalid native configuration',{exact:false})).toBeVisible()
 await expect(page.getByRole('button',{name:'Import reviewed template'})).toBeDisabled()
 expect(await page.evaluate(()=>(window as any).__calls)).toEqual([])
})

test('library apply protects dirty work and opens the explicit override diff', async ({page}) => {
 await openProject(page)
 await page.getByLabel('Native configuration',{exact:true}).fill('# Unsaved project rules')
 await library(page)
 await page.getByRole('button',{name:'Load into current file'}).click()
 await page.keyboard.press('Escape')
 await expect(page.getByRole('heading',{name:'Template library',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Load into current file'}).click()
 await page.getByRole('button',{name:'Discard changes',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Review your changes'})).toBeFocused()
 await expect(page.getByText('It replaces the whole file',{exact:false})).toBeVisible()
 await expect(page.getByRole('button',{name:'Save reviewed changes'})).toBeEnabled()
 expect(await page.evaluate(()=>(window as any).__calls)).toEqual(['preview'])
})

test('definition map distinguishes unopened contents, loaded roles and unverified references', async ({page}) => {
 await openProject(page)
 await page.evaluate(()=>(window as any).__agents=[{name:'reviewer',description:'Reviews only',configFile:'../private/reviewer.toml'}])
 await page.getByRole('button',{name:'Definition map',exact:true}).click()
 await expect(page.getByText('Contents not opened',{exact:true})).toHaveCount(2)
 await page.getByRole('button',{name:'Open definition .codex/config.toml',exact:true}).click()
 await expect(page.getByRole('heading',{name:'config.toml',exact:true})).toBeFocused()
 await page.getByLabel('Native configuration',{exact:true}).fill('model = "unsaved"')
 await page.getByRole('button',{name:'Definition map',exact:true}).click()
 await expect(page.getByRole('region',{name:'Definition map',exact:true}).getByText('../private/reviewer.toml',{exact:true})).toBeVisible()
 await expect(page.getByText('References · not opened or verified',{exact:true})).toBeVisible()
 await expect(page.getByRole('heading',{name:'Provider support in AgentForge'})).toBeVisible()
 expect(await page.evaluate(()=>(window as any).__reads)).toEqual(['AGENTS.md','.codex/config.toml'])
 await page.getByRole('button',{name:'Open definition AGENTS.md',exact:true}).click()
 await page.keyboard.press('Escape')
 await expect(page.getByRole('heading',{name:'Definition map',exact:true})).toBeVisible()
 await page.getByRole('button',{name:/^Project configuration/}).click()
 await expect(page.getByLabel('Native configuration',{exact:true})).toHaveValue('model = "unsaved"')
})

test('new views reflow, support keyboard and pass automated accessibility checks', async ({page},testInfo) => {
 await openProject(page)
 for(const name of ['Template library','Definition map']) {
  await page.getByRole('button',{name,exact:true}).focus();await page.keyboard.press('Enter')
  await expect(page.getByRole('heading',{name,exact:true})).toBeFocused()
  for(const width of [1280,768,320]) {
   await page.setViewportSize({width,height:900})
   await page.evaluate(()=>window.scrollTo(0,0))
   expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
   await page.screenshot({path:testInfo.outputPath(name.replaceAll(' ','-').toLowerCase()+'-'+width+'.png'),fullPage:true})
  }
  const results=await new AxeBuilder({page}).analyze()
  expect(results.violations).toEqual([])
 }
})
