import AxeBuilder from '@axe-core/playwright'
import { test, expect } from './fixtures'
import type { Page } from '@playwright/test'

async function openProject(page: Page, file = 'AGENTS.md') {
  await page.goto('/')
  await page.getByLabel('Project directory', { exact: true }).fill('/projects/sample-project')
  await page.getByRole('button', { name: 'Inspect project', exact: true }).click()
  if (file) await page.getByRole('button', { name: file, exact: true }).click()
}

test('workspace comes first; keyboard editing requires review before save', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Your project, its native configuration.' })).toBeVisible()
  await expect(page.getByLabel('Learning title')).toBeHidden()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: 'Skip to workspace' })).toBeFocused()
  await page.keyboard.press('Enter')
  await page.keyboard.press('Tab')
  await expect(page.getByLabel('Project directory', { exact: true })).toBeFocused()
  await page.keyboard.type('/projects/sample-project')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Browse…' })).toBeFocused()
  await page.keyboard.press('Tab')
  await page.keyboard.press('Enter')
  await expect(page.getByLabel('Filter files')).toBeVisible()
  await page.keyboard.press('Tab') // file filter
  await page.keyboard.press('Tab') // Claude agent
  await page.keyboard.press('Tab') // Codex settings
  await page.keyboard.press('Tab') // AGENTS.md
  await expect(page.getByRole('button', { name: 'AGENTS.md', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'AGENTS.md', exact: true })).toBeFocused()
  await page.keyboard.press('Tab') // definition disclosure
  await page.keyboard.press('Tab') // native text
  const source = page.getByLabel('Native configuration', { exact: true })
  await expect(source).toBeFocused()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('workspace-desktop.png'), fullPage: true })
  await page.keyboard.press('Control+End')
  await page.keyboard.type('\nReviewed keyboard change.')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Preview changes', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Review your changes' })).toBeFocused()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('review-desktop.png'), fullPage: true })
  expect(await page.evaluate(() => (window as any).__calls)).toEqual(['preview'])
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Save reviewed changes' })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('status')).toContainText('Saved.')
  await expect(page.getByText('Matches loaded file')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'AGENTS.md', exact: true })).toBeFocused()
  expect(await page.evaluate(() => (window as any).__calls)).toEqual(['preview', 'preview', 'save'])
})

test('file switch keeps the draft on Escape and discards only after confirmation', async ({ page }, testInfo) => {
  await openProject(page)
  const source = page.getByLabel('Native configuration', { exact: true })
  await source.fill('Keep this unsaved draft')
  await page.getByRole('button', { name: '.codex/config.toml', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Keep editing' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Discard changes', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Keep editing' })).toBeFocused()
  await page.screenshot({ path: testInfo.outputPath('discard-dialog.png') })
  await page.keyboard.press('Escape')
  await expect(source).toHaveValue('Keep this unsaved draft')
  await expect(page.getByRole('dialog')).toBeHidden()
  await page.getByRole('button', { name: '.codex/config.toml', exact: true }).click()
  await page.getByRole('button', { name: 'Discard changes', exact: true }).click()
  await expect(source).toHaveValue(/example-model/)
  await expect(page.getByText('Matches loaded file')).toBeVisible()
})

test('reload and unapplied structured fields are protected', async ({ page }) => {
  await openProject(page, '.claude/agents/reviewer.md')
  await page.locator('summary').filter({ hasText: 'Simple Claude agent fields' }).click()
  await page.getByLabel('Name', { exact: true }).fill('auditor')
  await page.getByRole('button', { name: 'Reload file', exact: true }).click()
  await page.getByRole('button', { name: 'Keep editing' }).click()
  await expect(page.getByLabel('Name', { exact: true })).toHaveValue('auditor')
  await page.getByRole('button', { name: 'Apply fields and preview' }).click()
  await expect(page.getByLabel('Native configuration', { exact: true })).toHaveValue(/name: auditor/)
  await page.getByLabel('Description', { exact: true }).fill('Reviews carefully')
  await expect(page.getByRole('button', { name: 'Save reviewed changes' })).toBeHidden()
  await expect(page.getByRole('button', { name: 'Preview changes', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Apply fields and preview' }).click()
  await page.getByRole('button', { name: 'Discard changes', exact: true }).click()
  await page.getByRole('button', { name: 'Save reviewed changes' }).click()
  await expect(page.getByText('Matches loaded file')).toBeVisible()
})

test('failed project inspection and save retain the editor draft', async ({ page }) => {
  await openProject(page)
  const source = page.getByLabel('Native configuration', { exact: true })
  await source.fill('Preserve this work')
  await page.evaluate(() => { (window as any).__failInspect = true })
  await page.getByLabel('Project directory', { exact: true }).fill('/missing-project')
  await page.getByRole('button', { name: 'Inspect project', exact: true }).click()
  await page.getByRole('button', { name: 'Discard changes', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('not accessible')
  await expect(source).toHaveValue('Preserve this work')
  await page.evaluate(() => { (window as any).__failSave = true })
  await page.getByRole('button', { name: 'Preview changes', exact: true }).click()
  await page.getByRole('button', { name: 'Save reviewed changes' }).click()
  await expect(page.getByRole('alert').filter({ hasText: 'File changed' })).toBeVisible()
  await expect(source).toHaveValue('Preserve this work')
  await expect(page.getByRole('button', { name: 'Save reviewed changes' })).toBeHidden()
})

test('validation blocks saving and pending save locks editing', async ({ page }) => {
  await openProject(page)
  const source = page.getByLabel('Native configuration', { exact: true })
  await source.fill('INVALID fixture')
  await page.getByRole('button', { name: 'Preview changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save reviewed changes' })).toBeDisabled()
  expect(await page.evaluate(() => (window as any).__calls.includes('save'))).toBe(false)
  await source.fill('Valid fixture')
  await page.getByRole('button', { name: 'Preview changes', exact: true }).click()
  await page.evaluate(() => { (window as any).__delaySave = 600 })
  await page.getByRole('button', { name: 'Save reviewed changes' }).click()
  await expect(source).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Saving…', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: '.codex/config.toml', exact: true })).toBeDisabled()
  await expect(page.getByText('Matches loaded file')).toBeVisible()
  expect(await page.evaluate(() => (window as any).__calls.filter((call: string) => call === 'save').length)).toBe(1)
})

test('template replacement requires confirmation and a separate save', async ({ page }) => {
  await openProject(page)
  const source = page.getByLabel('Native configuration', { exact: true })
  await source.fill('My draft')
  await page.locator('summary').filter({ hasText: 'Configuration templates' }).click()
  await page.getByLabel('Compatible template', { exact: true }).selectOption('template-1')
  await page.getByRole('button', { name: 'Load and preview' }).click()
  await page.getByRole('button', { name: 'Keep editing' }).click()
  await expect(source).toHaveValue('My draft')
  await page.getByRole('button', { name: 'Load and preview' }).click()
  await page.getByRole('button', { name: 'Discard changes', exact: true }).click()
  await expect(source).toHaveValue(/Team defaults/)
  await expect(page.getByRole('button', { name: 'Save reviewed changes' })).toBeVisible()
  expect(await page.evaluate(() => (window as any).__calls.includes('save'))).toBe(false)
})

test('library navigation preserves drafts and has an explicit empty state', async ({ page }, testInfo) => {
  await openProject(page)
  await page.getByLabel('Native configuration', { exact: true }).fill('Draft stays in workspace')
  await page.evaluate(() => { (window as any).__delayLearning = 600 })
  await page.getByRole('button', { name: 'Learning library', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Loading saved learnings…')
  await expect(page.getByRole('button', { name: 'Refresh library' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Save learning' })).toBeDisabled()
  await expect(page.getByRole('heading', { name: 'Build your reference library' })).toBeVisible()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('learning-library.png'), fullPage: true })
  await page.getByLabel('Learning title').fill('Learning draft also persists')
  await page.getByRole('button', { name: /Project configuration/ }).click()
  await expect(page.getByLabel('Native configuration', { exact: true })).toHaveValue('Draft stays in workspace')
  await page.getByRole('button', { name: 'Learning library', exact: true }).click()
  await expect(page.getByLabel('Learning title')).toHaveValue('Learning draft also persists')
})

test('filters and empty projects explain how to recover', async ({ page }) => {
  await openProject(page, '')
  await page.getByLabel('Filter files').fill('no-such-file')
  await expect(page.getByText('No files match', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Clear filter' }).click()
  await expect(page.getByRole('button', { name: 'AGENTS.md', exact: true })).toBeVisible()
  await page.getByLabel('Project directory', { exact: true }).fill('/projects/empty')
  await page.getByRole('button', { name: 'Inspect project', exact: true }).click()
  await expect(page.getByText('No supported files found.', { exact: false })).toBeVisible()
})

test('rendered views have no automated accessibility violations', async ({ page }) => {
  await openProject(page, '.codex/config.toml')
  await page.locator('summary').filter({ hasText: 'Definition & provider checks' }).click()
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.getByLabel('Native configuration', { exact: true }).fill('Edited fixture')
  await page.getByRole('button', { name: 'AGENTS.md', exact: true }).click()
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.getByRole('button', { name: 'Keep editing' }).click()
  await page.getByRole('button', { name: 'Learning library', exact: true }).click()
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
})

test('responsive layouts and long project paths reflow without horizontal page overflow', async ({ page }, testInfo) => {
  await openProject(page, '.codex/config.toml')
  await page.getByLabel('Project directory', { exact: true }).fill('/projects/' + 'long-directory-name-'.repeat(10))
  await page.getByRole('button', { name: 'Inspect project', exact: true }).click()
  await page.getByRole('button', { name: '.codex/config.toml', exact: true }).click()
  for (const width of [1280, 1100, 768, 320]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await expect(page.getByLabel('Native configuration', { exact: true })).toBeVisible()
    await page.evaluate(() => window.scrollTo(0, 0))
    await page.screenshot({ path: testInfo.outputPath(`workspace-${width}.png`), fullPage: true })
  }
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.addStyleTag({ content: ':root { font-size: 28px; }' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await expect(page.getByRole('button', { name: 'Reload file', exact: true })).toBeVisible()
})

test('semantic text and focus tokens have measured contrast', async ({ page }) => {
  await page.goto('/')
  const colors = await page.evaluate(() => {
    const style = getComputedStyle(document.documentElement)
    return Object.fromEntries(['text', 'text-muted', 'surface', 'surface-raised', 'input', 'focus', 'control-border', 'action', 'on-action'].map(name => [name, style.getPropertyValue(`--color-${name}`).trim()]))
  })
  const luminance = (hex: string) => {
    const rgb = hex.match(/[\da-f]{2}/gi)!.map(v => parseInt(v, 16) / 255).map(v => v <= .04045 ? v / 12.92 : ((v + .055) / 1.055) ** 2.4)
    return .2126 * rgb[0] + .7152 * rgb[1] + .0722 * rgb[2]
  }
  const contrast = (a: string, b: string) => (Math.max(luminance(a), luminance(b)) + .05) / (Math.min(luminance(a), luminance(b)) + .05)
  for (const text of ['text', 'text-muted']) for (const surface of ['surface', 'surface-raised', 'input']) {
    expect(contrast(colors[text], colors[surface])).toBeGreaterThanOrEqual(4.5)
  }
  expect(contrast(colors.action, colors['on-action'])).toBeGreaterThanOrEqual(4.5)
  expect(contrast(colors.focus, colors.input)).toBeGreaterThanOrEqual(3)
  expect(contrast(colors['control-border'], colors.input)).toBeGreaterThanOrEqual(3)
})
